### ISSUE TITLE
picodom ➥ Ultradom

### ISSUE THREAD

**Issue by jorgebucaran** [hydux/hydux#2]
Hey! @zaaack. Good job on this project! This is a friendly heads up that [Ultradom](https://github.com/jorgebucaran/ultradom) is the [continuation of and successor](https://github.com/jorgebucaran/ultradom/releases/tag/2.0.0) to Picodom. 

Could you update your documentation and upgrade your dependencies? And also, could you add `ultradom` to your repo's tags?  

Cheers! 👋

**Comment by zaaack** [comment]
@jorgebucaran Thanks a lot!!! I'll update it right now.
