### ISSUE TITLE
Support for V2 of HyperApp API

### ISSUE THREAD

**Issue by seanstrom** [hydux/hydux#5]
Are there plans to support V2 of HyperApp?

**Comment by zaaack** [comment]
@seanstrom What features do you want from HyperApp@v2? After a quick look, I only find the differences in entry function:

```ts
app(state, actions, view, container)
```

**Comment by seanstrom** [comment]
@zaaack 
Comparing the two libraries I'm unable to see any missing features necessarily. The features I'm most interested in HyperApp are the declarative apis for Actions, Subscriptions, and Effects. In this case it seems that all of these apis receive data and return tuples, I believe Init also follows this convention. There's also the design of how data will be passed to actions. For example, actions aren't curried by default.

What I'm hoping to achieve is using an api like HyperApp@v2 while still using React or Preact underneath. So far I'm convinced that Hydux is by far the closest thing I've found to accomplishing this, thank you very much, and I wanted to get your thoughts on potentially getting as close as possible. If I'm missing anything, or if you need more information from me, feel free to share. I would like to be as helpful as possible.

**Comment by zaaack** [comment]
@seanstrom 

> For example, actions aren't curried by default.

Hydux's action can be not curried, too. But then we cannot access the current state and actions, which is not often in my practice.

Thanks for your attention to Hydux, one of the reasons that I create Hydux just like you said, to using HyperApp with React/Preact. But there are also some other goals that I want to achieve. The main hope of Hydux is to provide a type-safe, javascript-friendly and React/Preact-compatible Elm Architectural implementation in the javascript ecosystem. So we have to keep some differences from HyperApp:

1. Elm like effects-manager, the command API, it's a tuple returned from actions/init before, but it's not easy for TypeScript to infer a tuple type (before 3.0), so I changed it to object. Although you can still using promise or side effects in void actions, just like HyperApp.
2. Type first, which means we have to make some extra adjustments to adapt typescript's type system, like the tuple -> obj change in actions.

Therefore, Hydux might not totally follow HyperApp's upgrades, but I'm very open to learning from HyperApp, Elm or any other excellent projects to make Hydux better. If you have some good ideas, please tell me, I'm really looking forward to improving this library with the community, thanks. 😄
