### ISSUE TITLE
Can we use hydux with react native?

### ISSUE THREAD

**Issue by kunjee17** [hydux/hydux#6]
First of thanks for wonderful framework and bringing Elm/ Elmish to TypeScript. 

I am big fan of Elm and Elmish architecture. Even gave couple of talks on it. I was curious that is it possible to use hydux with React Native ?

Or it would be over kill. We already have Fabulous (Elmish + Xamarin Forms + F#. ). So, I was thinking in same line. (Fable + Elmish + React Native is also possible as per last update ).

**Comment by zaaack** [comment]
> I was curious that is it possible to use hydux with React Native

Yes. Hydux is just like Elm/Elmish in typescript as you say, so it can be integrated with any vdom-based framework/library.  The only reason that we don't have something like hydux-react-native is that I don't have time to implement it (and there is no React Native projects on my hand). Also, the community of hydux is too small, I'm not even sure whether someone is still using it. 😅

**Comment by kunjee17** [comment]
@zaaack thanks for answering. 
> Also, the community of hydux is too small, I'm not even sure whether someone is still using it.

I know there are too many frameworks. But you still going to support this or planning to move away? If second option then any suggestion for other framework? I like to stick with Elmish style of architecture. Because Redux + etc etc is too hard to implement and explain as well.

**Comment by zaaack** [comment]
@kunjee17 I like Elm/Elmish architecture, too. But the react community also has big changes, like react-hooks, it might break the old Redux style, also I'm not sure it's impact to the Elm architecture implementation in TS + React. I don't think I'll move away until find a better replacement in TS + React, but I haven't using hydux for a while, because the project that I'm working on recently in my company only uses react, doesn't even need a state management library.

**Comment by kunjee17** [comment]
@zaaack please don't mind me asking. What you are using right now? Because sometime I think that if share state / passing data is a problem then we can easily get away with it, by using RxJs / Observable. Make model observable and event should change that. Or some other component can change that. It will raise a question about discipline but still.

**Comment by zaaack** [comment]
@kunjee17 Currently we use nothing, the project we are working on is a hybrid app, web pages in our app are small and most states are just UI logic, we can't and don't need(most time, if happens we share state on the server side) to share state between pages. RxJs / Observable is great, but I think they are a little heavy for my most practices. The hardest thing might be to choose the best approach for a certain case, we need to "predict" the future complexity of a project and avoid excessive or insufficient.

**Comment by kunjee17** [comment]
Thanks @zaaack for answers. I am closing this issue for now. Again thanks for your great work.
